// data.js — the per-unit-type reference library.
//
// THE WHOLE DESIGN: the engine and renderer are type-agnostic. A unit type is
// just data. To add a new measurable thing (mass, speed, pressure, data size…)
// you add one object here and nothing else changes.
//
// Schema per unit type:
//   id        unique key
//   label     display name
//   emoji     header glyph
//   blurb     one-liner shown under the title
//   strategy  "spatial" | "scale"
//   dim       2 (area) | 3 (volume)   -- only for spatial; controls √ vs ∛ sizing
//   orient    "h" | "v"               -- only for scale
//   canonical name of the base unit (for display)
//   units     { token: {factor} | {toBase,fromBase}, aliases:[...] }
//             factor = how many base units in one of this unit (multiplicative)
//             toBase/fromBase = for non-linear units (temperature)
//   anchors   [{ name, value(in base unit), emoji, note? }]   sorted is not required

const lin = (factor, aliases) => ({ factor, aliases });

window.MEASUREMENT_DATA = {
  area: {
    id: "area",
    label: "Area",
    emoji: "🗺️",
    blurb: "How much ground does that cover?",
    strategy: "spatial",
    dim: 2,
    canonical: "m²",
    fmtUnit: "m²",
    units: {
      "m2":      lin(1,         ["m2", "m^2", "sqm", "squaremeter", "squaremeters", "squaremetre", "squaremetres"]),
      "ft2":     lin(0.092903,  ["ft2", "ft^2", "sqft", "squarefeet", "squarefoot"]),
      "acre":    lin(4046.8564, ["acre", "acres", "ac"]),
      "hectare": lin(10000,     ["hectare", "hectares", "ha"]),
      "km2":     lin(1e6,       ["km2", "km^2", "sqkm", "squarekilometer", "squarekilometers", "squarekilometre"]),
      "mi2":     lin(2.59e6,    ["mi2", "mi^2", "sqmi", "squaremile", "squaremiles"]),
      "yd2":     lin(0.836127,  ["yd2", "yd^2", "sqyd", "squareyard", "squareyards"]),
    },
    anchors: [
      { name: "Sheet of A4 paper",      value: 0.0623,      emoji: "📄" },
      { name: "Parking space",          value: 12,          emoji: "🅿️" },
      { name: "Tennis court",           value: 260.87,      emoji: "🎾" },
      { name: "Basketball court",       value: 436.6,       emoji: "🏀" },
      { name: "Football field",         value: 5351,        emoji: "🏈" },
      { name: "Soccer pitch",           value: 7140,        emoji: "⚽" },
      { name: "City block",             value: 21900,       emoji: "🏙️" },
      { name: "Hyperscale data hall",   value: 93000,       emoji: "🖥️", note: "A single ~1-million-sq-ft hyperscale datacenter building." },
      { name: "Vatican City",           value: 440000,      emoji: "⛪" },
      { name: "Datacenter mega-campus", value: 4050000,     emoji: "🏭", note: "A ~1,000-acre hyperscale campus (Meta/Microsoft scale)." },
      { name: "Central Park",           value: 3410000,     emoji: "🌳" },
      { name: "Monaco",                 value: 2020000,     emoji: "🎰" },
      { name: "Manhattan",              value: 59100000,    emoji: "🌆" },
      { name: "Walt Disney World",      value: 101000000,   emoji: "🏰" },
      { name: "Paris (city limits)",    value: 105400000,   emoji: "🗼" },
      { name: "San Francisco",          value: 121000000,   emoji: "🌉" },
      { name: "Singapore",              value: 728600000,   emoji: "🇸🇬" },
      { name: "New York City",          value: 783800000,   emoji: "🗽" },
    ],
  },

  decibels: {
    id: "decibels",
    label: "Loudness",
    emoji: "🔊",
    blurb: "How loud is that, really?",
    strategy: "scale",
    orient: "h",
    canonical: "dB",
    fmtUnit: "dB",
    range: [0, 150],
    units: {
      "dB": lin(1, ["db", "dba", "dbspl", "decibel", "decibels"]),
    },
    anchors: [
      { name: "Threshold of hearing",  value: 0,   emoji: "🤫", note: "The quietest sound a human ear can detect." },
      { name: "Breathing",             value: 10,  emoji: "😮‍💨", note: "Your own breath in a silent room." },
      { name: "Rustling leaves",       value: 20,  emoji: "🍃", note: "A faint breeze through trees." },
      { name: "Whisper",               value: 30,  emoji: "🤐", note: "A quiet whisper a metre away." },
      { name: "Quiet library",         value: 40,  emoji: "📚", note: "Ambient hush of a reading room." },
      { name: "Refrigerator hum",      value: 50,  emoji: "🧊", note: "The background drone of a kitchen." },
      { name: "Datacenter at fence-line", value: 55, emoji: "🏭", note: "The constant 24/7 cooling hum neighbors fight over — often right at nighttime noise limits." },
      { name: "Normal conversation",   value: 60,  emoji: "💬", note: "Two people talking at arm's length." },
      { name: "Vacuum cleaner",        value: 70,  emoji: "🧹", note: "Busy traffic from the sidewalk." },
      { name: "City traffic",          value: 80,  emoji: "🚗", note: "Prolonged exposure starts to fatigue." },
      { name: "Lawnmower",             value: 90,  emoji: "🌱", note: "Hearing damage after ~8 hours." },
      { name: "Backup generators (test)", value: 95, emoji: "⚙️", note: "Diesel gensets during monthly load tests — a recurring complaint near datacenters." },
      { name: "Nightclub",             value: 100, emoji: "🪩", note: "Damage in ~15 minutes." },
      { name: "Rock concert",          value: 110, emoji: "🎸", note: "Damage in ~2 minutes." },
      { name: "Ambulance siren",       value: 120, emoji: "🚑", note: "The threshold of pain." },
      { name: "Jackhammer",            value: 130, emoji: "🔨", note: "Immediate risk to hearing." },
      { name: "Jet engine at takeoff", value: 140, emoji: "✈️", note: "Pain and instant damage up close." },
      { name: "Gunshot",               value: 150, emoji: "🔫", note: "A single peak can permanently damage hearing." },
    ],
  },

  liters: {
    id: "liters",
    label: "Volume",
    emoji: "🫗",
    blurb: "How much liquid is that?",
    strategy: "spatial",
    dim: 3,
    canonical: "L",
    fmtUnit: "L",
    units: {
      "L":       lin(1,        ["l", "liter", "liters", "litre", "litres"]),
      "mL":      lin(0.001,    ["ml", "milliliter", "milliliters", "millilitre"]),
      "gal":     lin(3.78541,  ["gal", "gallon", "gallons", "usgal"]),
      "qt":      lin(0.946353, ["qt", "quart", "quarts"]),
      "cup":     lin(0.236588, ["cup", "cups"]),
      "floz":    lin(0.0295735,["floz", "flozus", "fluidounce", "fluidounces"]),
      "m3":      lin(1000,     ["m3", "m^3", "cubicmeter", "cubicmeters", "cubicmetre"]),
    },
    anchors: [
      { name: "Teaspoon",          value: 0.005,    emoji: "🥄" },
      { name: "Shot glass",        value: 0.044,    emoji: "🥃" },
      { name: "Coffee cup",        value: 0.24,     emoji: "☕" },
      { name: "Soda can",          value: 0.355,    emoji: "🥤" },
      { name: "Water bottle",      value: 0.5,      emoji: "💧" },
      { name: "Wine bottle",       value: 0.75,     emoji: "🍷" },
      { name: "Milk jug (gallon)", value: 3.785,    emoji: "🥛" },
      { name: "Bucket",            value: 10,       emoji: "🪣" },
      { name: "Kitchen sink",      value: 20,       emoji: "🚰" },
      { name: "Beer keg",          value: 58.7,     emoji: "🍺" },
      { name: "Bathtub",           value: 150,      emoji: "🛁" },
      { name: "Oil drum",          value: 208,      emoji: "🛢️" },
      { name: "Hot tub",           value: 1500,     emoji: "♨️" },
      { name: "Tanker truck",      value: 30000,    emoji: "🚛" },
      { name: "Backyard pool",     value: 50000,    emoji: "🏊" },
      { name: "Olympic pool",      value: 2500000,  emoji: "🏅" },
    ],
  },

  temperature: {
    id: "temperature",
    label: "Temperature",
    emoji: "🌡️",
    blurb: "How hot or cold is that?",
    strategy: "scale",
    orient: "v",
    canonical: "°C",
    fmtUnit: "°C",
    units: {
      "C": { toBase: v => v,              fromBase: v => v,              aliases: ["c", "celsius", "centigrade", "degc", "°c"] },
      "F": { toBase: v => (v - 32) * 5/9, fromBase: v => v * 9/5 + 32,   aliases: ["f", "fahrenheit", "degf", "°f"] },
      "K": { toBase: v => v - 273.15,     fromBase: v => v + 273.15,     aliases: ["k", "kelvin", "degk", "°k"] },
    },
    anchors: [
      { name: "Absolute zero",        value: -273.15, emoji: "🥶", note: "All molecular motion stops. Nothing is colder." },
      { name: "Coldest day on Earth", value: -89,     emoji: "🏔️", note: "Vostok Station, Antarctica, 1983." },
      { name: "Dry ice sublimates",   value: -78.5,   emoji: "💨", note: "Solid CO₂ turns straight to gas." },
      { name: "Home freezer",         value: -18,     emoji: "🧊", note: "Standard freezer setting." },
      { name: "Water freezes",        value: 0,       emoji: "❄️", note: "Ice forms; snow falls." },
      { name: "Refrigerator",         value: 4,       emoji: "🥶", note: "Safe food-storage temperature." },
      { name: "Room temperature",     value: 21,      emoji: "🛋️", note: "Comfortable indoors." },
      { name: "Body temperature",     value: 37,      emoji: "🌡️", note: "Healthy human core temperature." },
      { name: "Hot bath",             value: 40,      emoji: "🛁", note: "About as hot as skin tolerates." },
      { name: "Hot coffee",           value: 65,      emoji: "☕", note: "Fresh from the machine." },
      { name: "Water boils",          value: 100,     emoji: "♨️", note: "Steam at sea level." },
      { name: "Oven (baking)",        value: 180,     emoji: "🍞", note: "Standard bread/cake setting." },
      { name: "Paper ignites",        value: 233,     emoji: "🔥", note: "Fahrenheit 451 — paper bursts into flame." },
      { name: "Pizza oven",           value: 450,     emoji: "🍕", note: "Wood-fired Neapolitan oven." },
      { name: "Lava",                 value: 1100,    emoji: "🌋", note: "Molten rock from a volcano." },
      { name: "Surface of the Sun",   value: 5500,    emoji: "☀️", note: "Hot enough to vaporize any material." },
    ],
  },

  // ======================= DATACENTER POLITICS PACK =======================
  // The magnitudes people actually fight about when a datacenter gets sited.
  // strategy "magnitude" = log axis (spans many orders of magnitude) + an
  // "it's like N of X" equivalence readout.

  power: {
    id: "power",
    label: "Power draw",
    emoji: "⚡",
    blurb: "How much electricity does it pull, right now?",
    strategy: "magnitude",
    canonical: "W",
    fmtUnit: "W",
    fmtBase: b => window.Engine.fmtSI(b, "W"),
    units: {
      "W":  lin(1,    ["w", "watt", "watts"]),
      "kW": lin(1e3,  ["kw", "kilowatt", "kilowatts"]),
      "MW": lin(1e6,  ["mw", "megawatt", "megawatts"]),
      "GW": lin(1e9,  ["gw", "gigawatt", "gigawatts"]),
      "TW": lin(1e12, ["tw", "terawatt", "terawatts"]),
      "hp": lin(745.7,["hp", "horsepower"]),
    },
    anchors: [
      { name: "LED bulb",                value: 10,      emoji: "💡" },
      { name: "Laptop",                  value: 50,      emoji: "💻" },
      { name: "Refrigerator",            value: 150,     emoji: "🧊" },
      { name: "Average US home",         value: 1250,    emoji: "🏠", relatable: true, note: "Continuous average draw of one US household." },
      { name: "EV fast charger",         value: 7000,    emoji: "🔌" },
      { name: "Tesla Supercharger",      value: 250000,  emoji: "🚗" },
      { name: "Wind turbine (rated)",    value: 3e6,     emoji: "🌬️" },
      { name: "Small datacenter",        value: 5e6,     emoji: "🖥️" },
      { name: "Large datacenter (100 MW)", value: 1e8,   emoji: "🏭", note: "A big hyperscale site — roughly 80,000 homes' worth of continuous draw." },
      { name: "Nuclear reactor",         value: 1e9,     emoji: "☢️", note: "A 'gigawatt-class' AI campus draws about this — one whole reactor, ~750,000 homes." },
      { name: "Hoover Dam",              value: 2.08e9,  emoji: "🌊" },
      { name: "New York City (peak)",    value: 1.1e10,  emoji: "🗽" },
      { name: "Three Gorges Dam",        value: 2.25e10, emoji: "🏞️" },
      { name: "Entire US grid (avg)",    value: 4.7e11,  emoji: "🇺🇸" },
    ],
  },

  energy: {
    id: "energy",
    label: "Annual electricity",
    emoji: "🔋",
    blurb: "How much electricity does it eat in a year?",
    strategy: "magnitude",
    canonical: "Wh/yr",
    fmtUnit: "Wh/yr",
    fmtBase: b => window.Engine.fmtSI(b, "Wh") + "/yr",
    units: {
      "kWh": lin(1e3,  ["kwh", "kwh/yr", "kwh/year", "kilowatthour", "kilowatthours"]),
      "MWh": lin(1e6,  ["mwh", "mwh/yr", "mwh/year", "megawatthour"]),
      "GWh": lin(1e9,  ["gwh", "gwh/yr", "gwh/year", "gigawatthour"]),
      "TWh": lin(1e12, ["twh", "twh/yr", "twh/year", "terawatthour"]),
      "Wh":  lin(1,    ["wh", "wh/yr", "wh/year", "watthour", "watthours"]),
    },
    anchors: [
      { name: "Average US home",          value: 1.08e7,  emoji: "🏠", relatable: true, note: "~10,800 kWh per year." },
      { name: "Large datacenter (100 MW)", value: 8.76e11, emoji: "🏭", note: "Running flat-out all year." },
      { name: "Gigawatt AI campus",       value: 8.76e12, emoji: "🤖", note: "~8.8 TWh/yr — more than many countries' datacenter fleets." },
      { name: "Ireland (whole country)",  value: 3.3e13,  emoji: "🇮🇪", note: "Datacenters already eat >20% of Ireland's national grid." },
      { name: "New York City",            value: 5.2e13,  emoji: "🗽" },
      { name: "United Kingdom",           value: 3.0e14,  emoji: "🇬🇧" },
      { name: "United States",            value: 4.0e15,  emoji: "🇺🇸" },
      { name: "The whole world",          value: 2.5e16,  emoji: "🌍" },
    ],
  },

  waterflow: {
    id: "waterflow",
    label: "Water use",
    emoji: "💧",
    blurb: "How much water does it drink per day?",
    strategy: "magnitude",
    canonical: "L/day",
    fmtUnit: "L/day",
    fmtBase: b => window.Engine.fmtShort(b) + " L/day (" + window.Engine.fmtShort(b / 3.78541) + " gal/day)",
    fmtTick: b => window.Engine.fmtShort(b / 3.78541) + " gal/day",
    units: {
      "L/day":   lin(1,         ["l/day", "l/d", "liters/day", "litres/day", "lpd"]),
      "gal/day": lin(3.78541,   ["gal/day", "gallons/day", "gpd"]),
      "mgd":     lin(3785411.8, ["mgd", "mg/day", "milliongallons/day"]),
      "m3/day":  lin(1000,      ["m3/day", "m^3/day", "cubicmeters/day"]),
    },
    anchors: [
      { name: "One person (US, daily)",   value: 300,     emoji: "🧍" },
      { name: "US household",             value: 1135,    emoji: "🏠", relatable: true },
      { name: "Golf course irrigation",   value: 1e6,     emoji: "⛳" },
      { name: "Small datacenter (0.5 MGD)", value: 1.9e6, emoji: "🖥️" },
      { name: "Town of 10,000 people",    value: 3e6,     emoji: "🏘️" },
      { name: "Large datacenter (3 MGD)", value: 1.1e7,   emoji: "🏭", note: "Evaporative cooling can drink as much as a town of ~35,000." },
      { name: "Hyperscale datacenter (5 MGD)", value: 1.9e7, emoji: "🏭", note: "The number that lands a project in front of an angry water board." },
      { name: "City of 100,000",          value: 3e7,     emoji: "🌆" },
      { name: "City of 1 million",        value: 3e8,     emoji: "🏙️" },
    ],
  },

  money: {
    id: "money",
    label: "Money",
    emoji: "💰",
    blurb: "How much money is that, in things you can picture?",
    strategy: "magnitude",
    canonical: "USD",
    fmtUnit: "USD",
    fmtBase: b => "$" + window.Engine.fmtShort(b),
    units: {
      "usd":      lin(1,    ["usd", "dollar", "dollars", "buck", "bucks"]),
      "thousand": lin(1e3,  ["thousand", "k", "grand"]),
      "million":  lin(1e6,  ["million", "mm"]),
      "billion":  lin(1e9,  ["billion", "bn"]),
      "trillion": lin(1e12, ["trillion", "tn"]),
    },
    anchors: [
      { name: "Median US home",        value: 4.2e5,  emoji: "🏠", relatable: true },
      { name: "Private jet",           value: 6e7,    emoji: "✈️" },
      { name: "Boeing 747",            value: 4e8,    emoji: "🛫" },
      { name: "Skyscraper",            value: 1e9,    emoji: "🏢" },
      { name: "Hyperscale datacenter", value: 1e10,   emoji: "🏭", note: "Building one big AI datacenter runs ~$10B all-in." },
      { name: "Aircraft carrier",      value: 1.3e10, emoji: "🚢" },
      { name: "Apollo program (adj.)", value: 2.6e11, emoji: "🚀" },
      { name: "Stargate project",      value: 5e11,   emoji: "🌌", note: "The announced OpenAI/Oracle/SoftBank datacenter buildout — half a trillion dollars." },
      { name: "US defense budget (yr)", value: 8.5e11, emoji: "🛡️" },
      { name: "Apple market cap",      value: 3e12,   emoji: "🍎" },
      { name: "US GDP",                value: 2.7e13, emoji: "🇺🇸" },
    ],
  },

  co2: {
    id: "co2",
    label: "Carbon emissions",
    emoji: "🌫️",
    blurb: "How much CO₂ is that per year?",
    strategy: "magnitude",
    canonical: "t CO₂/yr",
    fmtUnit: "t CO₂/yr",
    fmtBase: b => window.Engine.fmtShort(b) + " t CO₂/yr",
    units: {
      "t":  lin(1,    ["t", "ton", "tons", "tonne", "tonnes", "t/yr", "tons/yr", "tonnes/yr", "tco2", "tco2/yr"]),
      "kt": lin(1e3,  ["kt", "kiloton", "kilotons", "kt/yr"]),
      "Mt": lin(1e6,  ["mt", "megaton", "megatons", "mt/yr"]),
      "kg": lin(1e-3, ["kg", "kg/yr", "kgco2"]),
    },
    anchors: [
      { name: "Transatlantic flight (1 seat)", value: 1, emoji: "✈️" },
      { name: "Average car (per year)",   value: 4.6,    emoji: "🚗" },
      { name: "Average American (per yr)", value: 16,    emoji: "🧍", relatable: true },
      { name: "100 Americans",            value: 1600,   emoji: "👥" },
      { name: "Large datacenter (dirty grid)", value: 3.5e5, emoji: "🏭", note: "A 100 MW site on a fossil-heavy grid — like ~22,000 Americans' footprints." },
      { name: "Coal power plant",         value: 4e6,    emoji: "🏭" },
      { name: "Denmark (whole country)",  value: 3e7,    emoji: "🇩🇰" },
      { name: "Global aviation",          value: 1e9,    emoji: "🌍" },
    ],
  },
};
